### PR TITLE
option to add numbered handle text

### PR DESCRIPTION
**Pull request by fraserr**

### CODE REVIEW

**Comment by simeydotme** [comment]
Hey @fraserr ! :)
Thanks for contributing.

Can I please ask; What this PR's code is supposed to do, and do you have a JSFiddle to demonstrate it? 

Also; for PRs to be merged, they should pass the JSHint grunt task and conform to the current standard of code written... you left out curly braces `{`and `}` in the code. :)

**Comment by fraserr** [comment]
Hi @simeydotme,

Thanks for the slider!  I have updated my PR to adhere to your coding standard.

The changes i have made in this PR allow for the handle to show it's position, this is represented as text.  i have found this useful whilst implementing the slider in my project.

http://jsfiddle.net/fraserr/23LpLro6/

Thanks

**Comment by simeydotme** [comment]
I see... :)
Then I would suggest you use CSS to achieve this, kind of like i've done on the example: http://simeydotme.github.io/jQuery-ui-Slider-Pips/#styling-alternating-labels (hover the handles) ... there's already a lot of code executing, and DOM updates happening on the slider-handle-move, I don't think it's a good idea to add any more.

I will soon create a proper JSFiddle to show you how to achieve it without any code change; only CSS :)

Apologies, but I can't accept the PR :)

**Comment by simeydotme** [comment]
@fraserr , please check out: http://jsfiddle.net/simeydotme/gL4dunhu/ -- it should be exactly what you need :smile: -- it's purely CSS.

**Pull request closed without merging**
